### ISSUE TITLE
possibility to use own objective functions?

### ISSUE THREAD

**Issue by xRotor** [RaneemQaddoura/EvoCluster#5]
The EvoCluster itself might be a great idea, but how can it be applied for actual real optimization tasks? How can someone apply the optimization algorithms to non-benchmark/own cost functions?
Best thanks in advanced,
Fabian

**Comment by RaneemQaddoura** [comment]
You can follow the following videos for Evocluster:
https://youtu.be/3DYIdxILZaw
https://youtu.be/TOIo9WMBWUc

In EvoCluster, it has a specific idea; to optimize the clusters of the centroids using meta-heuristic algorithms, and it is used as a data science tool. 

If you are looking to optimize something else, rather than the clustering task, you need to go back to the more general one, EvoloPy, and add any objective function you'd like.

**Comment by xRotor** [comment]
Works with EvoloPy, thanks!
